### ISSUE TITLE
(Property Import) Ability to set SoapClient options

### ISSUE THREAD

**Issue by mattsims** [propertyhive/WP-Property-Hive#100]
Hi,

Our initial JET (Reapit) import was struggling to complete due to timeout issues, despite increasing PHP's `max_execution_time` and `default_socket_timeout`.

We found that setting the `connection_timeout` option in the [SoapClient constructor](https://www.php.net/manual/en/soapclient.soapclient.php) helped, however this required modifying the plugin code (`class-ph-jet-import.php`) to add a filter, i.e:

```
$soapclient_options = array();

$client = new SoapClient($options['url'], apply_filters( 'propertyhive_jet_soapclient_options', $soapclient_options ));
```

Am I able to submit a pull request somewhere?

Regards,

Matt.

**Comment by propertyhive** [comment]
Hi Matt, 

Thanks for contributing this. As the Import add on is a private repository we don't accept public PR's, however I have taken the code you've sent across and added it as part of the next release.

Thanks again!
Steve

**Comment by mattsims** [comment]
Awesome, thanks!

**Comment by mattsims** [comment]
Hi,
I've just noticed in the latest Property Import release that the SoapClient is re-initialised multiple times – not sure if it's always been this way, or if this was changed recently – but the `propertyhive_jet_soapclient_options` filter is only applied on the very first call (line 141).  Can this filter be added to all the other instances also?

Many thanks!

**Comment by propertyhive** [comment]
Absolutely right. I've applied this for the next release of the import add on., likely due out in the next 7-10 days Thanks for raising this.

Steve

**Comment by mattsims** [comment]
Top man, thanks Steve!
