### ISSUE TITLE
[Property Import] Look to get around timeout issues by forking separate processes

### ISSUE THREAD

**Issue by mattsims** [propertyhive/WP-Property-Hive#101]
Just as an FYI in case it's helpful...

In reference to [this card](https://trello.com/c/LfA5UcxF) on your roadmap, I have had past success using the method outlined [here](https://github.com/deliciousbrains/wp-background-processing).

This could be used to offload the media importing/resizing tasks to a background process, without having to get involved in `exec()` calls etc. This is exactly what we did prior to using PropertyHive for our feed importing, and it worked a treat :)

**Comment by propertyhive** [comment]
Really interesting. I've not heard of this before and could be just what we're looking for! Thanks so much for suggesting this. I've updated the card accordingly.

Better get reading :)

Thanks again!
Steve
