### ISSUE TITLE
Need Support for property hive plugins

### ISSUE THREAD

**Issue by geetaskycap** [propertyhive/WP-Property-Hive#105]
Hi Property Hive Team,

I want to import properties from 10ninety's properties software to my WordPress website. To Import this data I have checked you have provided a plugin named "Property Import". I want to use this plugin and ready to purchase your plugin but before that I want to check its functionality according to my requirements. Please provide me any demo package of this plugin or anything else so that I can check this plugin's functionality and the compatibility of this plugin with the 10ninety's properties software.
Please contact me on this email : geeta@skycap.co.in

**Comment by propertyhive** [comment]
Got in touch via email
