### ISSUE TITLE
Missing property type mappings RTDF

### ISSUE THREAD

**Issue by brynnroom57** [propertyhive/WP-Property-Hive#117]
I've noticed when setting up RTDF that there is 3 missing commercial property type mappings that are featured in the rightmove documentation.

80 Restaurant
83 Cafe
301 Childcare Facility

Is there a way to add these?

**Comment by propertyhive** [comment]
@brynnroom57 

You're absolutely right. Childcare Facility is already in the list but the others weren't. I've added these (and a few others that were missing) and released a new version of the Real-Time feed add on (version 1.1.30).

I'm going to send you the latest version of the add on via email now (expect it shortly) which you can upload via FTP overwriting the existing version.

Many thanks,
Steve
