### ISSUE TITLE
Problem adding Home Reports with Property Hive Home Reports Add On

### ISSUE THREAD

**Issue by espc-jcampbell** [propertyhive/WP-Property-Hive#124]
Hello, 

Similar to the issue with Floorplans and other media mentioned [here](https://github.com/propertyhive/WP-Property-Hive/issues/122) the same thing appears to be happening with the Home Reports addon, could an update be released for this plugin omply with recent WP 5.5 jQuery changes?

Thanks,

J

**Comment by propertyhive** [comment]
Hi J, 

We put out a new version of the Home Reports add on on Thursday. You should be able to update through WordPress to the latest version which should rectify this. 

Of course if problems persist do let me know,
Steve
