### ISSUE TITLE
Locations Multi-select

### ISSUE THREAD

**Issue by CHEWX** [propertyhive/WP-Property-Hive#13]
Might be a good idea to have the Locations Custom Field as a Multiselect. As unless you are using counties, or a location that is distinct, properties tend to lie between boundaries. For example using the following set-up, a user wouldn't know where West Mids start and East Mids ends -- https://www.routesintolanguages.ac.uk/sites/all/themes/uos_base_theme/images/uk_map_regional_consortia_web.gif

**Comment by propertyhive** [comment]
Agreed. Locations are already stored as taxonomy terms on the property so it should just be a case of updating the control without too much other effort or the need to do any sort of migration.

Adding this as a feature for release in the next 2 weeks.

**Comment by propertyhive** [comment]
Fixed in https://github.com/propertyhive/WP-Property-Hive/pull/18

To be released in version 1.1.2 later today

**Comment by CHEWX** [comment]
Sweet, nice one.
