### ISSUE TITLE
Rightmove Real-time Feed - Overseas flag

### ISSUE THREAD

**Issue by espc-jcampbell** [propertyhive/WP-Property-Hive#131]
Hello, 

I've encountered an issue with the latest version of the real-time feed and Rightmove, from the release notes: 

`Changed overseas feed to use address 3 as region if no address 4 entered`

What data is assigned to address 4 in this case? I've got address 3 populated with the 'Town/City' which I assumed would be enough but I'm getting the following error: 

`VAL_00031 - We were unable to add/update your property record because an invalid answer value was given in the overseas flag. The allowed values for this field are TRUE and FALSE.`

I'm also NOT using Overseas at all as it's a local client, so that's unchecked in the feed settings - if you could please advise as to what I should be using for address 3 and 4 in order to resolve this. 

Many thanks,

J

**Comment by propertyhive** [comment]
@espc-jcampbell Thanks for getting in touch. This is certainly most odd. The address change you mention wouldn't be related I don't believe as the error being returned seems to be specific to the 'overseas' flag.

Would it possible to get WordPress access to the site so I can take a look for myself? That's probably the easiest way to look into this. You can email these through to info@wp-property-hive.com referencing this GitHub issue and I'll be able to take a look.

Once I've had a look I'll post my findings here and we can continue to discuss it in this thread.

Many thanks,
Steve

**Comment by espc-jcampbell** [comment]
Hi Steve, 

Sure - I'll send you the details. As I mentioned though I have rolled the plugin back a few versions, there's plenty to see in the logfiles obviously but if you could refrain from updating the plugin as properties will stop sending to Rightmove!

Thanks,

Jonny

**Comment by propertyhive** [comment]
@espc-jcampbell This is so odd. I've done a comparison of the version you were running (1.1.21) to the latest version (1.1.33) and we've made no changes whatsoever to the overseas flag in the data sent to Rightmove. I'm a bit stumped if I'm honest.

There's only two things I can think to do from here:

1) I notice you have the Home Reports add on active. I know that modifies the Rightmove request to include Home Reports. It shouldn't make a difference at all but if you deactivate that add on does it then work?
2) If you're happy to send over FTP access I can take a closer look at the code and add some additional debugging to the logs to try and work out exactly what's going on here.

Sorry I can't give a definitive answer at this time. Keen to get to the bottom of this though and find out what's causing it as we have Rightmove feeds running on loads of  other sites without this issue so curious to know what's different in this scenario.

Steve

**Comment by propertyhive** [comment]
Ignore me!! Problem found and new version (1.1.34) released with immediate effect.

Steve
