### ISSUE TITLE
Imported Photo URL "h" rather than actual URL of image

### ISSUE THREAD

**Issue by Bowend00** [propertyhive/WP-Property-Hive#137]
Hi, I'm trying to import my photos as URLs however, they're all just being imported as "h". 

Is there a way to match this to the correct photo URL? See link [https://freeimage.host/i/3sFbZN](url)

**Comment by propertyhive** [comment]
@Bowend00 Can you confirm where you're importing them from?

**Comment by Bowend00** [comment]
From Juvo.io using the property important plugin

**Comment by propertyhive** [comment]
Thanks for confirming. I see the issue and have put this in as a bug to fix for the next release of the Property Import add on going out tomorrow (https://trello.com/c/jBa4Gzb9).

As soon as this is available I'll update this issue.

Thanks for reporting this,
Steve

**Comment by propertyhive** [comment]
@Bowend00 Just to confirm a new version of the import add on (1.2.13) was released last night that fixes the issues regarding Juvo that you raised. If you have a license key you can update to the latest version through WP. If not, ping me an email at info@wp-property-hive.com and I'll send the latest version through to you.

Thanks,
Steve
