### ISSUE TITLE
Jet / Reapit import additional Virtual Tour URL

### ISSUE THREAD

**Issue by brynnroom57** [propertyhive/WP-Property-Hive#142]
In Jet / Reapit CMS there are two fields for Virtual Tours, currently, only the first one gets populated in propertyhive even if both are filled out in Reapit. Is there a way to add the additional Virtual Tour from Reapit into the propertyhive listing?

Cheers

**Comment by propertyhive** [comment]
@brynnroom57 I've just released version 1.219 of the import add on which now adds support for their second virtual tour field, as well as captions should they be entered.

I'm going to send you the latest version via email now...

Thanks,
Steve
