### ISSUE TITLE
Need Support for WP Residence data bridge property Add on

### ISSUE THREAD

**Issue by kaleemnadeem16** [propertyhive/WP-Property-Hive#143]
Hey. I have your wp-residence data bridge add on. But it can't seems to be working. I have installed it but when I go to the settings (currently) it just says:

Logs | No syncs ran yet. Logs will appear here when a sync is ran

Next scheduled to run at 14:40 16th January 2021

But the time is already passed. I tried to change some settings but every time I tried something, the time for the next schedule I get is already passed 1 min to be exactly.

**Comment by kaleemnadeem16** [comment]
Well i figured it out. It was a server issue. Cron jobs was not working properly.

**Comment by propertyhive** [comment]
Glad to hear you worked it out. Let me know if we can help further.
