### ISSUE TITLE
Higher res images in archive

### ISSUE THREAD

**Issue by MB-sites** [propertyhive/WP-Property-Hive#148]
Hiya,
How can I set there images shown in the results at higher resolution.n All good on single property page, but the archive looks rather blurry. I have looked through the files, but couldn't find where to change this.
Thanks in advance,

Mike

**Comment by propertyhive** [comment]
Hi Mike, 

Have you seen this doc here:

https://docs.wp-property-hive.com/developer-guide/miscellaneous-and-snippets/using-a-different-size-image-as-property-thumbnail/

Let me know if any further questions after trying the above,
Steve

**Comment by MB-sites** [comment]
Amazing, just what I needed. Must have missed that in the docs.
Thank you ever so much
