### ISSUE TITLE
Bug: Missing class

### ISSUE THREAD

**Issue by CHEWX** [propertyhive/WP-Property-Hive#15]
Hi Steve,

With the recent update you have added some callbacks to a class that doesn't exist. This is causing the plugin to break and ACF fields won't save.

`PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, class 'PH_Meta_Box_Property_Commercial_Description' not found in /wp-admin/includes/template.php on line 1037`

Thanks,
Tom

**Comment by propertyhive** [comment]
Fixed in 02e1bea1140c6c043c90361daf02694f8ff9465a

Just pushed a new version so you should be able to update.

Thanks for letting me know!
