### ISSUE TITLE
Import Properties not removed when off market

### ISSUE THREAD

**Issue by Miltra** [propertyhive/WP-Property-Hive#153]
I have set that imported properties remove automatically if not received, but the property pages are not deleting, we import from Vebra. Only import updated properties box is unticked.

**Comment by propertyhive** [comment]
Is the 'on market' tickbox in WordPress being unticked? And have you seen this doc:

https://docs.wp-property-hive.com/developer-guide/handling-off-market-properties/

Let me know if any further questions, 
Thanks,
Steve

**Comment by Miltra** [comment]
Thanks Steve,

Not sure where the On market tickbox is, reading the documentation it says that it doesn't delete the old pages, thank you
