### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by CHEWX** [propertyhive/WP-Property-Hive#16]
Do you have a roadmap at all as I'd like to develop features, but not sure if it's been doing, or being done etc.

For example a simple Trello board -- https://trello.com/b/YgRbpuze/woocommerce-roadmap

The reason I asked this is I need a Sold Gallery, and it doesn't look to be in the core.

Thanks,
Tom

**Comment by propertyhive** [comment]
Hi Tom, 

We do have a roadmap internally here but it's a great idea to publish it for others to view. 

Regarding your sold gallery question, this is what 'Marketing Flags' under the 'Marketing' tab of a property record are intended for. Assuming you have a flag set up called 'Recently Sold' or 'Sold Gallery', you can then use the following shortcode to display properties assigned to that flag:

`[properties marketing_flag="TERM_ID_HERE"]`

I'd be curious to know if that works for you or if you had something else in mind?

For the purpose of this ticket our roadmap looks like so at present (in no particular order):

- On main property and contact pages in Wordpress, make columns sortable
- Support for Vebra feed added to Property Import add on
- New export add on for Property Link, a popular property portal amongst commercial agents
- Update to Radius Search Add On allowing you to give bias to locations. This is for when locations are entered that exist in multiple places across the UK For example there is an Edmonton in Cornwall and London
- Add new field of 'Let Type' to lettings properties
- V2 of our Map Search add on (draw-a-search, clustering and more)
- Go through all add ons and ensure they support the newly added commercial department
- Need to write documentation for all add ons

I'l look at getting this into a Trello board as that's a great idea. Let me know on the sold gallery though.

**Comment by CHEWX** [comment]
Sounds good.

Ah, yeah, can do it like that. I was searching for a tax_query on availability.

**Comment by propertyhive** [comment]
Roadmap setup. Can be found here:

https://trello.com/b/jb7bjB6j/property-hive-roadmap

Thanks
