### ISSUE TITLE
Description not pulling through from DezRez

### ISSUE THREAD

**Issue by holmesbrand** [propertyhive/WP-Property-Hive#162]
The first line (summary) is importing as expected, but the rest of the description is missing.
Does this need to be mapped to a custom field?

**Comment by propertyhive** [comment]
@holmesbrand Thanks for getting in touch. 

Can you confirm if you're using DezRez XML or JSON (One or Rezi)?

The full description should be imported into the 'Rooms' area of a property record. Sometimes we need to look at the actual data being received from Dezrez. If you're able to send the WP details or Dezrez API details through to info@wp-property-hive.com referencing this issue I can then take a look.

Thanks,
Steve

**Comment by holmesbrand** [comment]
Hey Steve

Were you able to investigate this issue at all? 

Thanks

**Comment by propertyhive** [comment]
Thanks for the details. The thing with Dezrez we find is that there seems to be little consistency as to how the descriptions are used. There are 6+ description fields and no two feeds seem to be the same. Just yesterday I was working on a Dezrez feed and the 2nd description (the one you're using as a full description by the looks of it) was used for listing features as bullet points.

After having a look at how your feed works I believe adding a snippet like so should result in the 2nd description being imported into the rooms/full description area of a property in Hive:

https://gist.github.com/propertyhive/2ce932da45281edeeeafc0e4528ac1a9

Do let me know how that looks after adding that and running another full import.

Steve

**Comment by holmesbrand** [comment]
Hey Steve

Thank you for your assistance with this, the snippet has been added in and
I have completed a full import but the description still isn't pulling
through.

Would you be able to take another look please? Unfortunately the client is
becoming a bit fractious so keen to get this resolved asap!

Appreciate your support and already have another client lined up for a
Property Hive deployment based on the quality of your product and support.

Thanks

**Comment by holmesbrand** [comment]
Hey Steve

Just wondered if you were able to take another look at this? Unfortunately
the description still isn't pulling through which is delaying delivery of
the project.

Would appreciate your assistance to get this resolved as soon as possible
please.

Sincere thanks

**Comment by propertyhive** [comment]
Are you able to send through WordPress access to info@wp-property-hive.com and I'll take a look for myself. I'll also try running the same Dezrez feed on our development site with the same snippet and see if I can get it working there.

Thanks,
Steve

**Comment by holmesbrand** [comment]
Hey thanks Steve, details below:

url: ngea.lgroup.dev/wp-admin
u. propertyhivesupport
p. propertyhive321!

Look forward to hearing from you.

Best

**Comment by propertyhive** [comment]
Thanks. I've hidden the login details from your comment as this is a public forum. 

Where has the snippet I originally referenced been added? I can't see it in functions.php, nor any kind of plugin that allows custom PHP snippets to be added?

Thanks
Steve

**Comment by holmesbrand** [comment]
Thanks Steve, here's the response from our developer:






*So, the code snippet was in /inc/honeycomb-functions.php which gets
included in functions.php as a partial file.I've re-uploaded it with a
comment :"// FUNCTION FROM PROPERTY HIVE TO USE DESCRIPTION 2"*
Hope that helps.

**Comment by propertyhive** [comment]
Apologies for the delay. Finally figured it out. Was missing a line from the snippet I sent you. Have updated it accordingly and include it again below:

https://gist.github.com/propertyhive/2ce932da45281edeeeafc0e4528ac1a9#file-gistfile1-txt-L20

Let me know if problems persist after adding that line.

Steve

**Comment by holmesbrand** [comment]
Hi Steve

Unfortunately the feed is still not pulling through from Dezrez One as
expected.

Please compare the description content on the following properties:

live website:
http://www.nickgriffithestateagents.co.uk/property-search/_product/928/pittville-circus-road-pittville-cheltenham/
development website:
https://ngea.lgroup.dev/property/pittville-circus-road-pittville-cheltenham/

The code snippet that you provided was successfully added to
honeycomb-functions.php and has pulled through the list items, but there is
still a lot of content missing.

Are you able to assist please?
