### ISSUE TITLE
Search Form Format

### ISSUE THREAD

**Issue by PaulNWard** [propertyhive/WP-Property-Hive#163]
Hi there,
I have propertyhive with honeycomb. All working fine and happy with website apart from the search form box. Is there anywhere I can change the grey box that the search fields sit on so its more colourful or opaque or not there at all.
Thank you,
Paul
![2021-07-02](https://user-images.githubusercontent.com/86826681/124246844-93806100-db21-11eb-994f-0f8a7e617426.png)

**Comment by propertyhive** [comment]
@PaulNWard Some CSS (can be added under 'Appearance > Customise > Additional CSS'):

.property-search-form { background:transparent }

Hope that helps,
Steve
