### ISSUE TITLE
Search Form Location - Need Modification

### ISSUE THREAD

**Issue by PaulNWard** [propertyhive/WP-Property-Hive#165]
Hi there,
Don't know if this could be added to a future update.
I have nested property locations - Province and Town (in UK would by County and Town)
In the search form it only has one location which will show you all the Provinces and their Towns, a really long list.
You can select to show just the top level (Provinces) but would be great if there was a second location field that populated the Towns belonging to the Province selected in the first location field.
Hope that makes sense.
Cheers,
Paul

**Comment by propertyhive** [comment]
@PaulNWard Interesting. I like the idea of this. I've added it to the roadmap (https://trello.com/c/HChNVxEO). I'm afraid I can't give any time estimations however as to when this can be looked at. Probably not for at least a few months if I'm honest.

Steve

**Comment by PaulNWard** [comment]
Hi Steve,

Glad you like the idea, it works all over the world. Look forward to
seeing the implementation in the future.

Cheers,
Paul

**Comment by propertyhive** [comment]
This has now been done as part of version 1.5.34 of Property Hive:

https://wp-property-hive.com/property-hive-version-1-5-34-cascading-location-search-dropdowns-elementor-updates/

**Comment by PaulNWard** [comment]
Hello,
I've updated my test site to work with the auto populating cascading
provinces then towns. Works a treat.
Is there a setting so that the towns can appear alphabetically?
I've attached a screenshot showing the town dropdown or you can see the
test site at https://maskhq.co.uk/
Cheers,
Paul Ward

**Comment by propertyhive** [comment]
Hi Paul, 

We store locations as standard WordPress taxonomy/terms in Property Hive. It's not possible to reorder terms by default in WordPress, though third party plugins do exist that claim to offer this functionality. (e.g. https://en-gb.wordpress.org/plugins/taxonomy-terms-order/).

Being a third party plugin we can't offer support further for this but hopefully that helps somewhat.

Thanks,
Steve
