### ISSUE TITLE
Additional fields needed in PH Kyero export plugin

### ISSUE THREAD

**Issue by PaulNWard** [propertyhive/WP-Property-Hive#166]
Hello,
I use Property Hive and Property Hive Kyero Export plugin and Template Assistant.
In the template assistant I have additional fields Build size and Plot size and need these to be created in the Kyero export feed but it  doesn't pick these up.
Is there any way of getting these fields added, even if it is by editing the code on the server?
Cheers,
Paul

**Comment by propertyhive** [comment]
@PaulNWard You can see an example of how to add additional fields to the Kyero XML below:

https://gist.github.com/propertyhive/004f290ad80df9d86e462919011f7a6e

Once added, wait for the XML to be generated again (should be hourly) and you'll see these new fields. If you need any further clarification on the above do let me know,

Steve

**Comment by PaulNWard** [comment]
Hi Steve,

Thanks for the code. I don't know which file or where to put it though.
Do I add it at the end of propertyhive-kyero-export.php?

Cheers,
Paul

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by propertyhive** [comment]
It will go in your themes functions.php file, or you can use a plugin like Code Snippets (https://wordpress.org/plugins/code-snippets/).

Thanks,
Steve

**Comment by PaulNWard** [comment]
Hi Steve,
Still not managed to get them to appear in the xml feed. I copied the text
into the themes functions.php file exactly as it was, tried that. Then I
tried it with custom_field_0 and custom_field_1 and then I tried it with
the names I'd given as below, but none of them have been picked up in the
feed. I'm obviously doing something wrong.
/*  Add your own functions below this line.
    ======================================== */
add_filter( 'ph_kyero_property_values', 'custom_kyero', 10, 3 );
function custom_kyero($property_xml, $post_id, $portal_id)
{
    $property = new PH_Property($post_id);

    $property_xml->addChild('build_m2');
    $property_xml->build_m2 = $property->build_m2;

    $property_xml->addChild('plot_m2');
    $property_xml->plot_m2 = $property->plot_m2;

    return $property_xml;
}
Cheers,
Paul

**Comment by propertyhive** [comment]
Hi Paul,

Are the fields at least appearing in the XML, they're just blank? Or there's no change? And did you wait an hour for the XML to be automatically re-generated after adding the code?

If still no closer, if you can send through WP access to info@wp-property-hive.com I'll gladly take a look for myself.

Thanks,
Steve

**Comment by PaulNWard** [comment]
Hi Steve,
The xml feed hasn't changed, still the original, they're not appearing and
I updated it first thing this morning.
https://spanishnewbuildhomes.com/wp-content/uploads/ph_kyero/0.xml

Appearance-Theme Editor-SNBH Theme-Theme Functions is where I put the code.

Login is       https://spanishnewbuildhomes.com/lfc1892/
User           Steve PH
Password   stevephkyero

Cheers,
Paul

**Comment by propertyhive** [comment]
Certainly very odd. I've just tried this exact same snippet on our development site, using the same version of the Kyero add on, and it worked right away:

![Screenshot_11](https://user-images.githubusercontent.com/13717200/126649297-01ca87b7-bde8-4fa1-8688-c33940c73c2b.png)

As it stands I can't see anything from here. I think the next step would be to get FTP access to do some debugging. Is it possible to get these?

Note: Please don't post them in this forum as this is public. They can be emailed through to info@wp-property-hive.com

Thanks,
Steve
