### ISSUE TITLE
Valuation Form Popup close button not working in chrome

### ISSUE THREAD

**Issue by wordpressdeveloper211** [propertyhive/WP-Property-Hive#169]
https://jumpshare.com/v/mAP1FqErdIbcAXKsGUib 

Valuation form popup close button not working in chrome.
get this warning message
**A different origin subframe tried to create a JavaScript dialog. This is no longer allowed and was blocked. See https://www.chromestatus.com/feature/5148698084376576 for more details.**

For the Valuation form, I used **"Property Hive PropertyFile Add On"** 

Is there a way to resolve this issue? 

Thanks
John

**Comment by propertyhive** [comment]
I'm afraid this would be a question for Property File as we have control of the popup. Steve

**Comment by wordpressdeveloper211** [comment]
Okay 
So where I need to add this issue?
