### ISSUE TITLE
Can the Map show town location if no coordinates entered

### ISSUE THREAD

**Issue by PaulNWard** [propertyhive/WP-Property-Hive#170]
Hi there,
The map shows on individual properties if the coordinates are entered, all good.
However, I have some feeds coming in where there are no coordinates. Is there a way of getting the map to position itself by town and province (county) if coordinates are blank?
I'm using Property Hive and Honeycomb.
Cheers,
Paul

**Comment by propertyhive** [comment]
Hi Paul, 

Apologies for the delay. What format are you using to import properties out of interest? I've tried to login using the previous details provided but the no longer work.

With most formats, if no lat/lng is provided we'll fallback to trying to obtain co-ordinates ourselves using the Google geocoding service. For this a valid Google Maps API key must be entered under 'Property Hive > Settings > General > Map'.

Hope that helps,
Steve

**Comment by PaulNWard** [comment]
Hi Steve,

I'm using the OpenStreetMap and I cannot find the properties without a map
at the moment. If I come across one again I'll make a note and get a google
map API and switch to that instead of the OSM version.

Cheers,
Paul

**Comment by propertyhive** [comment]
Hi Paul,

You should still be able to use OSM. You'll notice under 'Property Hive > Settings > General > Map', even if you have OSM selected you'll still have the ability to enter a API key for the Google geocoding service.

Do let me know if any issues going forward.

Steve
