### ISSUE TITLE
Property Archve Empty spaces

### ISSUE THREAD

**Issue by Lankesh9814** [propertyhive/WP-Property-Hive#176]
![image](https://user-images.githubusercontent.com/72129713/145972118-fd9b6512-a40e-452d-b659-5e0a2be88b6b.png)

Empty Spaces after every 3 properties in the archive. We need 2 column layout for the archive. Please give any solutions

**Comment by Lankesh9814** [comment]
https://hive.designsolv.com/search_results/?department=residential-lettings

This the page

**Comment by propertyhive** [comment]
Just checked that link and looks to be sorted? I'm not seeing the empty spaces?

Thanks,
Steve

**Comment by Lankesh9814** [comment]
Hi Steve,

I tried to manage it using your previous comment

**Can you also confirm if you have anything set under 'Property hive > Settings > Template assistant > Search Results' (if using the Template Assistant add on) in terms of number of properties shown per row?**
