### ISSUE TITLE
Property Hive and Vebra Missing Fields on the Front End 

### ISSUE THREAD

**Issue by Lankesh9814** [propertyhive/WP-Property-Hive#178]
The House Number field was missing in the front end but it was already in the backend

**Comment by propertyhive** [comment]
@Lankesh9814 I'm not sure I understand the issue/requirement here I'm afraid. Are you able elaborate? 

Thanks,
Steve

**Comment by Lankesh9814** [comment]
Hi Steve,

We are importing property details from Vebra to the Property-hive system. In the backend, details are showing correctly but in the frontend some fields are missing

**Comment by propertyhive** [comment]
@Lankesh9814 Thanks for more details. Do you have a link where I can see this for myself and an example of a field that isn't showing?

**Comment by Lankesh9814** [comment]
https://hive.designsolv.com/property/nassau-street-london/

The property no was in the frontend but it's captured on the backend

**Comment by Lankesh9814** [comment]
> https://hive.designsolv.com/property/nassau-street-london/
> 
> The property no was not in the frontend but it's captured on the backend

Means house No or Apartment no

**Comment by propertyhive** [comment]
@Lankesh9814 

There is a field in the Vebra data called 'display address'. This is what we use as the public address shown on the frontend. If you want house number to be included in this display address it will need to come through with this included from Vebra.

Thanks,
Steve

**Comment by Lankesh9814** [comment]
![image](https://user-images.githubusercontent.com/72129713/149140199-8b94a14e-4486-477e-b3c1-1cba94194315.png)

the highlighted fields, not show in the front end

This is the property link
`https://hive.designsolv.com/property/gloucester-terrace-london-w2/`

**Comment by propertyhive** [comment]
@Lankesh9814 

> the highlighted fields, not show in the front end

Correct. We don't show these fields to the public. The address shown to the public on the frontend is the one entered as the post title:

![Screenshot_12](https://user-images.githubusercontent.com/13717200/149152571-0c7f3751-1c4d-4ba4-9bc4-f33998b258c2.png)

As per my previous response:

> There is a field in the Vebra data called 'display address'. This is what we use as the public address shown on the frontend. If you want house number to be included in this display address it will need to come through with this included from Vebra.

As such this is a question for Vebra as to how to change the 'display address' field sent through in the data.

Thanks,
Steve

**Comment by Lankesh9814** [comment]
Other Thing the Property - hive filter not working properly with Post Code. When I filter via postcode I'm getting no results but the post code was still on the system

**Comment by Lankesh9814** [comment]
Our Site Link: https://hive.designsolv.com/

**Comment by propertyhive** [comment]
That postcode field in your search form isn't a standard Property Hive field. I'm assuming this is a bespoke field you've added yourself?

If so, how are you populating this? Is there a reason you've added a custom field as opposed to using the existing available 'address keyword' field?

Thanks,
Steve

**Comment by Lankesh9814** [comment]
Hi Steve,

You're right it's a custom field. How can I tie-up with the original postal code

**Comment by propertyhive** [comment]
I've just checked the site and can see you've changed it to use default Property Hive address keyword field in the search form. Entering and searching by postcode seems to return the correct results. Can you confirm this is all ok now?

Many thanks,
Steve
