### ISSUE TITLE
Under Offer, Sold STC & Sold Banners on Property Listing pages

### ISSUE THREAD

**Issue by Johnem58** [propertyhive/WP-Property-Hive#181]
I use a Property Hive on my estate agency website and was wanting to know how I can assign a banner against properties I have "Under Offer", "Sold STC" & "Sold" on Properties displayed on the Listing and Property details pages?

**Comment by propertyhive** [comment]
@Johnem58 I think what you're after is our Flags feature:

https://docs.wp-property-hive.com/add-ons/template-assistant/flags/

Let me know if I've got the wrong end of the stick or if any further questions, 

Thanks,
Steve

**Comment by Johnem58** [comment]
Thanks, Steve.
That works great,

John
