### ISSUE TITLE
Currency change issue

### ISSUE THREAD

**Issue by lesda** [propertyhive/WP-Property-Hive#183]
Changing the language/currency in the International submenu has no effect on the existing properties, their prices are still presented with the currency that was the default setting when the property was first created. This could be OK for some cases, but let's see this case:
 - initially, GBP is the currency, and we are uploading a few new properties and setting them properly
 - then we realize that we wanted to show the prices in EUR or HUF (or any other currency)
 - changing the settings of the International submenu accordingly won't change anything on existing properties as I experience
 - but I would expect to be able to change/switch manually the currency settings of a property, but there is no such option available (at least for the Rooms add-on I am certain)
So far the 'best' option I can up with is to delete the whole property and recreate it - but this should go smoother

**Comment by propertyhive** [comment]
@lesda Thanks for the feedback. Having replicated this scenario you're right, and I will add it to the roadmap to be investigated (https://trello.com/c/UkTQ6hCR) though I'm afraid I can't offer any timescales on this.

Thanks again, 
Steve
