### ISSUE TITLE
Rooms currency issue

### ISSUE THREAD

**Issue by lesda** [propertyhive/WP-Property-Hive#184]
The rooms add-on doesn't use the settings of the International submenu at all.

How to replicate:
 - change the settings of the International submenu to anything but Great Britan/pound
 - add a new property with Rooms
 - set the price of the Room (the admin page shows the right currency)
 - check the property/room page and the price will be shown in £

**Comment by propertyhive** [comment]
@lesda You're correct. Adding to the roadmap (https://trello.com/c/l6eHShX6) to be addressed next week. Once a fix has been put in place and a new version of the Rooms add on is available we'll be in touch.

Thanks for reporting this,

Steve

**Comment by lesda** [comment]
Is there any update on this? How can we get the updated component?

**Comment by propertyhive** [comment]
@lesda Yes this was done as part of version 1.0.11 of the Rooms add on released last week. If you have a license key you can update to the latest version through WordPress, else please email info@wp-property-hive.com referencing this issue and I'll send a copy through to you.

Thanks,
Steve
