### ISSUE TITLE
Commercial Property

### ISSUE THREAD

**Issue by peterartis** [propertyhive/WP-Property-Hive#185]
Hello, is there a way to set Commercial Property price same like Residential?
At the moment we can only set price per area, we also feed our properties to zoopla and price should be set same as residential, like for example £109000 offers over. Is that possible?

**Comment by propertyhive** [comment]
@peterartis If you have a property added to the 'commercial' department and it selected as 'For Sale' you can enter the price leaving the 'unit' dropdown empty and it will display/act the same as residential:

![Screenshot_17](https://user-images.githubusercontent.com/13717200/160156256-4e75ff39-372e-4f24-b526-38383a9cedb7.png)

Hope that helps but let me know if I've got the wrong end of the stick here.

Thanks,
Steve
