### ISSUE TITLE
Elementor crashes with propertyhive plugin activated

### ISSUE THREAD

**Issue by TheGregSchouten** [propertyhive/WP-Property-Hive#187]
When I activate the propertyhive plugin and go to the latest version of elementor the elements bar on the left keeps on loading.(see screenshot)  If I deactivate the propertyhive plugin it works again. I deactivated and reinstalled all plugins that are using elementor and they are not the problem. The icons in the elementor bar are not working except the 'tabbed details', the is also no data in any of the elements so they don't work(see other screenshot).
<img width="341" alt="image" src="https://user-images.githubusercontent.com/102995106/161691482-ff82eb14-70b5-4b76-b287-f4094d476688.png">
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/102995106/161691614-64c14af3-7767-4470-a682-fe510291cb4e.png">

When rolling back to elementor 3.5.1 elementor loads but property hive elements look like this:
<img width="325" alt="image" src="https://user-images.githubusercontent.com/102995106/161691874-b10e0b42-3f21-4571-a71a-e4a0d1e5a018.png">

With all elements data is not actually loaded.

**Comment by propertyhive** [comment]
Thanks for raising this. I think the particular issue you raise might be with the 'Rooms' add on which it looks like you're using. We had someone else raise this earlier in the week and, as a result, we released a new version of the 'Rooms' add on (v1.0.11) which fixes this.

If you don't have a license key and need me to send this through, please email info@wp-property-hive.com referencing this issue and I'll gladly send it through.

Thanks again,
Steve

**Comment by TheGregSchouten** [comment]
Please see email below, I have a license key but I would like to receive this update asap.

Thank you!



Met vriendelijke groet, With friendly regards,    

Greg Schouten  

[/Users/gschouten/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1520483934] 

www.corigen.nl<http://www.corigen.nl/>    
Direct telefoonnummer +31 (0)6 45 08 88 04


Van: Property Hive ***@***.***>
Datum: woensdag, 20 april 2022 om 12:09
Aan: propertyhive/WP-Property-Hive ***@***.***>
CC: Greg Schouten ***@***.***>, Author ***@***.***>
Onderwerp: Re: [propertyhive/WP-Property-Hive] Elementor crashes with propertyhive plugin activated (Issue #187)

Thanks for raising this. I think the particular issue you raise might be with the 'Rooms' add on which it looks like you're using. We had someone else raise this earlier in the week and, as a result, we released a new version of the 'Rooms' add on (v1.0.11) which fixes this.

If you don't have a license key and need me to send this through, please email ***@***.******@***.***> referencing this issue and I'll gladly send it through.

Thanks again,
Steve
