### ISSUE TITLE
Rooms add-on - deposit?

### ISSUE THREAD

**Issue by lesda** [propertyhive/WP-Property-Hive#188]
Hi there!
 
 Setting a deposit for a Room on the admin side is allowed, but it is not presented publicly on the property page. I am not sure what was the intention here (having or not having a deposit field), but the current solution seems inconsistent.

**Comment by propertyhive** [comment]
Thanks for reporting this. Have added to roadmap:

https://trello.com/c/fzcbRNuv

Steve
