### ISSUE TITLE
Price slider and rent slider currency symbol fixed to £

### ISSUE THREAD

**Issue by SpinDreams** [propertyhive/WP-Property-Hive#192]
The Price slider and Rent slider within the search bar are fixed to £ even if you have your country set other than UK (Me italy so should be EUR)

**Comment by propertyhive** [comment]
This is odd. I've just tested here and it worked:

![Screenshot_1](https://user-images.githubusercontent.com/13717200/174577314-245d7324-34ab-48d3-b38b-e3ef5b267f38.png)

![Screenshot_2](https://user-images.githubusercontent.com/13717200/174577443-96e90f60-efe0-4b04-828f-5da27fc35833.png)

Can you confirm the version of Property Hive you're running?

Steve

**Comment by SpinDreams** [comment]
Okay I went in and resaved the international options (unchanged as they were set correctly) and now the currency on the sliders has changed, I am going to guess a new version added some feature but the data it needed was not in the database and needed re-saving.  Thanks.
