### ISSUE TITLE
"See all x Images" is not translatable.

### ISSUE THREAD

**Issue by SpinDreams** [propertyhive/WP-Property-Hive#195]
Within the Property hive Elementor gallery widget the "See all x Images" is not translatable.

**Comment by propertyhive** [comment]
Thanks for reporting this. This has been completed for the next release of Property Hive, likely out later this week:

https://github.com/propertyhive/WP-Property-Hive/commit/ce29bf44bc75a77f58ae237ddcf9e6d0bbcb5c3a

Steve
