### ISSUE TITLE
Property Import Add On not importing data from alto

### ISSUE THREAD

**Issue by kiranz11** [propertyhive/WP-Property-Hive#210]
Hi there, the import function is not pulling any properties at all through to the site, everything seems to be set up correctly, please advise on this, i can provide a link and login to the site....

**Comment by propertyhive** [comment]
@kiranz11 I'd need lots more information to diagnose this. Yes if can send through WP access to info@wp-property-hive.com that would be great. I'll take a look and come to you via this thread.

Steve

**Comment by kiranz11** [comment]
Thanks have emailed you, appreciate the support....

**Comment by kiranz11** [comment]
Sorry for the late reply on this, the data feed is in now, and still not returning any properties?

**Comment by propertyhive** [comment]
@kiranz11 Did you get a complete set of API details, or just the datafeed ID? Because the username and password sent previously didn't look right.

What does it say in the import logs? If it's saying there's a 401 error then the issue is the details aren't valid and will be a question for Alto.
