### ISSUE TITLE
Clarks Computers XML not importing

### ISSUE THREAD

**Issue by elias1435** [propertyhive/WP-Property-Hive#213]
I am using "Clarks Computers XML" feed to import new properties.
Total 440 properties imported and the log is showing its imported "[15:05 13th February 2023)" that mean half hour ago its imported but same thing i am seeing last 2 days.
also another issue no property listing is showing in my website.

is there some one can help me to fix this?

Thanks

**Comment by propertyhive** [comment]
@elias1435 Thanks for getting in touch. Would it possible to send through the Clarks Computers/Muven API Key to info@wp-property-hive.com and I'll try it on our development here to see if it works or not. This will allow us to determine if it's site-specific or not.

Thanks,
Steve

**Comment by propertyhive** [comment]
As per email, I can see the issue in that when no lettings properties are sent it was falling into an infinite loop. This was fixed in version 1.3.14 of the Import add on which I sent across via email.
