### ISSUE TITLE
Open SSL Error

### ISSUE THREAD

**Issue by jamessy** [propertyhive/WP-Property-Hive#214]
We've suddenly started getting the following error:
`Error sending cURL request: 58 - could not load PEM client certificate from /home/customer/www/*******/public_html/wp-content/uploads/ph_realtime/33efb864cebf9df8f8f8fd923e174a5d48ae4e23.pem](https://github.com/propertyhive/WP-Property-Hive/issues/jacksonproperty.co.uk/public_html/wp-content/uploads/ph_realtime/33efb864cebf9df8f8f8fd923e174a5d48ae4e23.pem), OpenSSL error error:0A00018E:SSL routines::ca md`

Any idea's what could be causing it?

**Comment by propertyhive** [comment]
@jamessy For your reference, and anyone else also experiencing this, we have a troubleshooting doc relating to this here:

https://docs.wp-property-hive.com/add-ons/real-time-data-feed/troubleshooting/
