### ISSUE TITLE
Only importing properties which are available from Arthur

### ISSUE THREAD

**Issue by antonyjsmith** [propertyhive/WP-Property-Hive#224]
I'm just trialing the import add on and have been running some test imports from Arthur. It's all connect fine however only properties which are currently available to let are being imported.

I can't work out if it's Arthur removing these from the feed or Property Hive not requesting them?

I need to get everything imported to PH regardless of status!

Thanks for any help.

**Comment by propertyhive** [comment]
@antonyjsmith We only import properties/units from Arthur that have the following statuses:

Available to Let
Under Offer

Should you wish to include 'Let' properties (or other statuses) as well you could use a snippet like:

https://gist.github.com/propertyhive/3574b34835c69ab0bf61ab6e9bb8e8cf

Hope that helps but do let me know if I can assist further.

Steve
