### ISSUE TITLE
specific reapit pulls...

### ISSUE THREAD

**Issue by Richjaw** [propertyhive/WP-Property-Hive#228]
Hi, I was wondering how I would specify Propertyhive only pull specific branches and status' from Reapit.

For example, only manchester branches, not liverpool ones and only for sale, to let and under offer properties, not pulling under instruction etc.

we operate many offices across 2 brands and I need to separate them across 2 sites.

thanks in advance.

**Comment by propertyhive** [comment]
@Richjaw 

Filtering by branch(es): https://gist.github.com/propertyhive/075f10b8b1239c989e4a1130e69a33b0

Filtering by status: https://gist.github.com/propertyhive/aa15ae08232f08c0d78aecfda63e2ba8

Once the above snippets have been added and  amended, run another full import and you should see them take effect.

Do let me know if any issues/questions, 

Steve

**Comment by Richjaw** [comment]
The shame I feel having to ask this... but where do I add this code?

As you can guess, I've been dropped in the deep end on this.

Thanks for all the help.

**Comment by propertyhive** [comment]
Not a problem at all. They can go in your themes functions.php file, or use a plugin like Code Snippets:

https://wordpress.org/plugins/code-snippets/

Do let me know if I can assist further.
