### ISSUE TITLE
Custom Header Footers

### ISSUE THREAD

**Issue by CHEWX** [propertyhive/WP-Property-Hive#23]
Hi Steve, 

Be good to have custom headers and footers.

`header('property');`
`footer('property');`

As there is no hooks for this you have to edit the core template by copying into your theme.

Thanks,
Tom

**Comment by propertyhive** [comment]
Done in 1.1.5 which has just been released. `header-propertyhive.php` and `footer-propertyhive.php` can be used now.

Thanks for the suggestion!
