### ISSUE TITLE
Error on property price

### ISSUE THREAD

**Issue by peteparker** [propertyhive/WP-Property-Hive#235]
Hi to all, we sent to the support e-mail an issue we are having with property price field. It does not keep zeroes when we update a property, when we click UPDATE for example the value 1.000.000 becomes 10.
We think the problem lies on decimals and separators, since if we keep the price lower than 1.000 it goes OK.

Please send us a feedback because we need to go online with the website and wth this issue is not possible.

Thanls

Franco Calcagnì

**Comment by propertyhive** [comment]
I've replied via email but the purposes this ticket my reponsse was:

> The price entered in the backend should be entered without separators, or if you need to put separators in, please use a comma as the thousand separator. 
> 
> The options where you specify thousand and decimal separator in your screenshot is purely for outputting purposes.

I'll close this now and resume communication over email
