### ISSUE TITLE
Listings View Type

### ISSUE THREAD

**Issue by CHEWX** [propertyhive/WP-Property-Hive#24]
Hi Steve,

View type, is there anything in the core to do with this, or is this simply custom code that switches depending on the query string ? As I couldn't find anything.

`?view=grid`
`?view=list`

Thanks,
Tom

**Comment by propertyhive** [comment]
Hi Tom, 

Nope, nothing in the core looking out the `view` parameter. When I've done it on sites like http://www.ivygate.co.uk/ivy-gate-search it's been custom code.

Thinking about it, it might be something that could be added to the core. Maybe something like, if a view is passed in the query string it uses a template file called `content-property-VIEWNAME.php` and adds it as class to the `search/loop-start.php` template too so you can differentiate the CSS.

What do you think? Did you have any thoughts on this?

**Comment by CHEWX** [comment]
Yup, I think that works.

I wouldn't put `content-property-VIEWNAME.php` into the plugin, just allow `ph_get_template_part( 'content', 'property' )` in `archive-property.php` to take different view loops.

I think it should be put in to the plugin, but can't think of a nice way to do it. Maybe it shouldn't. As there is only a few lines of code to do it custom.

**Comment by propertyhive** [comment]
Cool. I'm closing this issue as it sounds like you've got it sorted but if it comes again we can look at a more permanent/intuitive solution. 

Thanks
