### ISSUE TITLE
ACF Fields not saving

### ISSUE THREAD

**Issue by CHEWX** [propertyhive/WP-Property-Hive#25]
ACF fields in property not saving.

I think this has cropped up before, but an update fixed it.

Seems to have arisen again with latest update.

Thanks,
Tom

**Comment by propertyhive** [comment]
Hmm.. Yeh we had this arise ages ago. The cause was the $post variable getting overwritten somewhere in one of the meta boxes.

I'll get ACF setup shortly and see if I can recreate this. Keep you posted.

**Comment by propertyhive** [comment]
This should be fixed in version 1.1.6
