### ISSUE TITLE
customise viewing request popup - honeycomb

### ISSUE THREAD

**Issue by Richjaw** [propertyhive/WP-Property-Hive#252]
Hi,

I currently have no way to customise the "Viewing Request" popup on Honeycomb.

Both the text and background are white so text is ineligible.

How would I go about fixing this as I can't find an option anywhere!?

![image](https://github.com/user-attachments/assets/54849897-e1d3-4720-8a33-c2ecc78b907b)

Image attached for some perspective.

Thanks in advance!

**Comment by propertyhive** [comment]
Hi Rich, 

Interesting. I'm assuming you've set the body font colour or similar to white and this is then being inherited into the enquiry popup.

Some CSS like so should rectify this:

`.property-enquiry-form h3,
.property-enquiry-form label { color:#000; }`

Do give that a go and let me know how you get on or if any further questions.
