### ISSUE TITLE
[Vebra import] Latest, single property listing and the property edit all reporting different availabilities

### ISSUE THREAD

**Issue by bluebee-team** [propertyhive/WP-Property-Hive#256]
Hello everyone, how are you all doing?

Encountering a really weird issue at the moment with the displays along the pathway of finding a rental property on a client site. If you would prefer a direct link, I'd be happy to get in touch privately and send you a link.

1) The edit mode of the property in question - this is pulling through from Vebra and is indeed pulling the correct availability
![Screenshot 2024-09-19 at 14 08 51](https://github.com/user-attachments/assets/9bbefc6a-5c44-4b38-915a-c953b86ad857)

2) The latest list containing the property, is showing Let Agreed
![Screenshot 2024-09-19 at 15 33 11](https://github.com/user-attachments/assets/1417f0f7-42ba-4c18-92b9-570d93ade38f)

3) The individual property, is showing To Let
![Screenshot 2024-09-19 at 15 32 52](https://github.com/user-attachments/assets/e4068aa9-ac5c-4706-a4b8-07dcb1bcdfaa)

Additional notes:

1) There are no hooks or template overrides affecting the view of this flag. Nothing in the functions at all
2) I've checked before submitting a ticket, it appears to only be us experiencing this issue
3) Property Hive is up to date on this site

Many thanks,

**Comment by bluebee-team** [comment]
Hi all, would like to reach out to the community as well as the development team.

Are anyone else at all encountering this, and what did you do to resolve it? I've searched through here, there are only really a couple of issues that mention Availability.

Any help at all would be very much appreciated. Thank you!

**Comment by bluebee-team** [comment]
Hi there everyone, hope you all had a lovely weekend.

Has anyone got an idea what's happening here?

**Comment by bluebee-team** [comment]
> @bluebee-team I would suggest emailing the support team with more information about your specific site and setup their email is [info@wp-property-hive.com](mailto:info@wp-property-hive.com)

Wonderful, thank you so much Marley. I wasn't aware we could email them for support. Much appreciated!

**Comment by propertyhive** [comment]
For the purposes of this ticket we have dealt with this via email and found the cause to be that the plugin was edited direct. Not an issue with Property Hive.
