### ISSUE TITLE
Field Mappings for Arthur Imports

### ISSUE THREAD

**Issue by antonyjsmith** [propertyhive/WP-Property-Hive#260]
I'm just trying to work out how the key fields map when importing from Arthur. Is there any way to filter these mappings?

We're importing units only and the **post title** seems to be based on the **Portal Address** which is under unit information in Arthur. However the **Unit Reference** is what's used as the title to list the units in Arthur so it's a bit confusing.

Any information would be appreciated

Thanks

**Comment by propertyhive** [comment]
@antonyjsmith You're right. We do use `portal_address` by default when setting the post title. Should you want to also include `unit_ref` you could use a snippet like so:

https://gist.github.com/propertyhive/38ea05eb8b12c565cd5f1208dbe5744b

Do let me know if any further examples required,
Steve

**Comment by propertyhive** [comment]
-- Please reply above this line --


            Hi,

Apologies for the very long delay here.

If you want to use the unit ref as a title you can use this PHP
snippet.
https://gist.github.com/g-maclean/4c61cf4950f33a36d4f229515a2be4b2 [1]

Let me know if you need more info on how to set that up.
Please note this is untested but should do the trick.


Links:
------
[1] https://gist.github.com/g-maclean/4c61cf4950f33a36d4f229515a2be4b2


 Thanks,

 GRANT MACLEAN

 Property Hive Software Ltd 

   [1]

 GOT A MINUTE? If you've found Property Hive useful or our support to
be particularly helpful we would love to receive your feedback [2]. 

 Follow us on LinkedIn [3]

 

Links:
------
[1] https://wp-property-hive.com/
[2] https://wordpress.org/support/plugin/propertyhive/reviews/
[3] https://www.linkedin.com/company/wp-property-hive/
