### ISSUE TITLE
Certain fields not included in _property_import_data

### ISSUE THREAD

**Issue by will-yellowpeach** [propertyhive/WP-Property-Hive#261]
We have a client who uses Reapit Foundations, and under the 'Extra Descriptions' section there are text boxes for things like 'Situation' which we need to display on our website - screenshot below.

Previously we have raised a ticket in Foundations and they have added that data to the feed if it wasn't available (we did that with 'Additional information'), but it looks like they have closed any issues being added now so wondering what we do to achieve that?

![Screenshot 2024-10-17 at 13 16 10](https://github.com/user-attachments/assets/376f5a01-48c9-456d-93f6-9ee1ae7064e2)

**Comment by propertyhive** [comment]
@will-yellowpeach If they've already added it to the feed, great! You can then import that into Property Hive using the following:

https://gist.github.com/propertyhive/94dfb1c6949c9fbe1e8cf8ecb77d185d

This will import it as part of the description. Hope that's enough to go on but if you need any further examples let me know.

Steve
