### ISSUE TITLE
Critical Error on Arthur Property Import

### ISSUE THREAD

**Issue by antonyjsmith** [propertyhive/WP-Property-Hive#262]
Hi there, since the most recent import update I've been getting the follow critical error:

`Parse error: syntax error, unexpected variable "$property", expecting ")" in /wp-content/plugins/propertyhive-property-import/includes/class-ph-arthur-json-import.php on line 2505
`

This line needed a comma adding, I can't create a pull request as this is a premium plugin:

`$this->propertyhive_property_import_add_log( 'Importing unit ' . ($unit_i + 1) . ' of ' . $num_units . ' with reference ' . $unit['id'], 0, $property['id'] . '-' . $unit['id'] );
`

**Comment by propertyhive** [comment]
@antonyjsmith Thanks for notifying us of this. This has been corrected in version 2.1.1 of the import add on that's just been released.

Apologies for any inconvenience.
