### ISSUE TITLE
Cannot change the Property post title

### ISSUE THREAD

**Issue by kush1960** [propertyhive/WP-Property-Hive#263]
I need the properties in my website to use a custom address format for the post title.
I'm using the Foundations API Importer.
Lokking through the code, this is where the title is assigned in `class-ph-reapit-foundations-json-import.php`

```
 if (!empty($property['strapline'])) {
                        $post_title = $property['strapline'];
                    } else {
                        $address_fields_array = array_filter(
                            array(
                                $property['address']['line1'],
                                $property['address']['line2'],
                                $property['address']['line3'],
                                $property['address']['line4'],
                                $property['address']['postcode'],
                            )
                        );

                        $post_title = implode(', ', $address_fields_array);
                    }
```

I was hoping to find a hook here, so I could set my own title logic, but I can't find anything.
It makes no sense on my website to use the strap as the post title.
And even if we were to use the address fallback, I need to customise the address format to show a partial postcode.

I'm writing a custom search component now, which illustrates the problem

![image](https://github.com/user-attachments/assets/da55de87-b11d-46e5-8a0e-232351385b29)
As you can see, the search results show the strap line which is useless in this context.

Could a hook be added? Or is there another workaround for this issue?

Many thanks.

**Comment by propertyhive** [comment]
I think this might be the snippet you're after:

https://gist.github.com/propertyhive/106fe62eb1a960fbf0d84100acdb35af

Please do give that a go, running a full import after adding the snippet, and let me know how you get on.

**Comment by kush1960** [comment]
That worked a treat! Thank you.
