### ISSUE TITLE
Support for Block Themes

### ISSUE THREAD

**Issue by webd-uk** [propertyhive/WP-Property-Hive#264]
Hello,

We are re-developing a website for a client with Property Hive and WordPress latest default theme Twenty Twenty-Five which is a block theme.

We have not been able to find a way to allow your plugin to make use of block theme templates so have used this in a custom plugin to enable us to do so ...

```
add_action('init', 'webd_init', 11);

function webd_init() {
    remove_all_actions('template_include', 10);
    remove_all_actions('template_include', 99);
}
```

As such we will need to re-create all your classic templates with block versions.

Please confirm if you have developed any blocks to aid in the design of block templates? Such as a "Single Property Summary Block" for example?

If not, we plan to develop one that just provides a dropdown of existing Property Hive templates in the Block Settings so we can map a Block Template to the content of one of the files in your `/templates/` folder.

Please advise before we start work because obviously we'd much rather use existing Property Hive blocks (even if they are only in beta).

Many thanks,

Oliver

**Comment by propertyhive** [comment]
Hi Oliver,

Thanks for getting in touch. Blocks is something we have on our (very long) to do list, but nothing done on this yet so no chance of conflict etc.

Thanks,
Steve

**Comment by webd-uk** [comment]
Thanks Steve. Understood. If anyone reading this thread would like to test out our "Blocks for Property Hive" plugin as it comes together, [feel free to get in touch with us](https://webd.uk).

**Comment by antonyjsmith** [comment]
Hi there @webd-uk  I'm currently tackling a very similar build using Property Hive and a Block Theme. Keen to see where you'd got to with your plugin before I start rolling my own solution!

I tried to message via your site but the contact form seems to time out.

Thanks!

**Comment by webd-uk** [comment]
Hi @antonyjsmith,

The plugin is very much still in a concept / rough prototype phase, however it currently does the following ...

1. Enhances the `office` custom post type so that offices' descriptions / featured images etc can be updated and offices have their own permalinks.
2. Adds a `staff` taxonomy with  so that members of staff can be assigned to offices
3. If the installed theme is a block theme then the plugin disables Property Hive default templates
4. The plugin registers a "Property Content" block which can be configured generate the following content via a drop down in the block settings which utilise the default Gutenberg colour, spacing, typography and border options via the styles panel ...
- Property Search Form
- Property Search Result Count
- Property Search Map
- Property Search Result Order
- Property Search Pagination
- Property Back To Search Button
- Property Address
- Property Address (short)
- Property Department
- Property Type
- Property Price
- Property Bedrooms Count
- Property Reception Rooms Count
- Property Bathrooms Count
- Office Map
- Office Map (all)
- Office Telephone
- Office Address
- Office Address (2 lines)
- Staff Back To Office
- Staff Job Title
- Staff Sound Bite
5. The plugin extends core blocks as follows ...
- Image block: Property Images, Floorplan, EPC
- Featured Image block: Property Images
- Cover block: Property Images
- Gallery block: Property Images
6. Functions to use with Block Logic plugin so as to display blocks conditionally ...
- has_office_address()
- has_office_map()
- has_office_email()
- has_office_properties()
- has_staff_sound_bite()
- has_property_floorplan()
- has_epc()
- has_property_bedrooms()
- has_property_reception_rooms()
- has_property_bathrooms()
7. We also have produced a few shortcodes whilst learning how Property Hive was put together which will be moved into the Property Content block in due course if they aren't required to show text in the middle of a Paragraph or Title block (for example) ...
- Property Title
- Property Photo Count (with suffix option)
- Property Floorplan
- Property Price
- Property Address
- Property Bedrooms Count (with suffix option)
- Property Reception Rooms Count (with suffix option)
- Property Bathrooms Count (with suffix option)
- Property Google Map Link
- Property Leaflet Map
- Property Office
- Property Enquiry
- Search Form
- Result Count
- Catalogue Ordering
- Office Title

There's probably a bunch of other stuff that it does too :)

It's not ready for third party testing yet ... it currently makes use of "Custom Post Type UI", "Advanced Custom Fields" and "Leaflet Map" plugins so we could rapidly get to where we are. We weren't expecting this Block Theme issue and it's set us back a bit with our project.

Thanks for letting us know about the form. It's a Contact Form 7 form so not sure why it would do that, usually that plugin is pretty robust. Do let me know if you spot an error in the console!

Oliver
