### ISSUE TITLE
Not showing for Editors

### ISSUE THREAD

**Issue by CHEWX** [propertyhive/WP-Property-Hive#27]
Hi Steve,

Has Property Hive purposely been set-up for Administrator level users only ?

I think Editors should be able to access it by default.

Thanks,
Tom

**Comment by propertyhive** [comment]
Hi Tom, 

This wasn't done on purpose, and I agree it should be visible to editors also.

Short term solution is to use a plugin such as https://en-gb.wordpress.org/plugins/capability-manager-enhanced/

I have added this to the roadmap however (https://trello.com/b/jb7bjB6j/property-hive-roadmap) and will aim to get this in within the next couple of weeks, unless someone actions earlier.

Thanks,
Steve

**Comment by propertyhive** [comment]
This has now been sorted in the latest version (1.1.10). Editors have access to everything in Property Hive, except the 'Settings' area.

If you encounter issues updating an existing version, please deactivate then reactivate and that will will sort.

Thanks
