### ISSUE TITLE
WP Menu - 'current-menu-item' and 'current_page_item' classes are being removed

### ISSUE THREAD

**Issue by Shahab2905** [propertyhive/WP-Property-Hive#28]
Hi PropertyHive Team,

It seems default generated WP Menu classes  'current-menu-item' and 'current_page_item' are automatically being removed from the menu on Property Search / Archive Page.

The problem is also present on 'http://honey.wp-property-hive.com/property-search/' page if you compare it with other pages. The current header menu will not highlight as the classes are missing.

http://www.awesomescreenshot.com/image/1480541/7151db931ed4b0879db9074a3565c0ac

and not working:

http://www.awesomescreenshot.com/image/1480543/f8474cd3c387c53ae4876798a278a8ba

Any help is appreciated.

**Comment by propertyhive** [comment]
Hi Shahab,

Thanks for this. This is a generic WordPress issue in that menu items linking to archive pages don't get the 'current-menu-item' class by default.

I agree that this could be resolved so will see if I can put a fix in (although it won't be a for at least a week as I'm away on holiday).

If it's urgent, I recommend performing a Google for "[current-menu-item archive page](https://www.google.co.uk/search?q=current-menu-item+archive+page)" and try one of the solutions there. It seems to be a commonly requested question.

Sorry I can't be of immediate help but I'll update this thread as soon as  a fix is in place and released.

Thanks again!

**Comment by Shahab2905** [comment]
I appreciate your quick response :+1: 

Its not urgent, if you can add a solution in the next couple of weeks, that will be awesome.

Thank you

**Comment by Shahab2905** [comment]
Hi PropertyHive Team,

The solution below works for me:

https://gist.github.com/Shahab2905/f8f3d495d3484b9f6ca7188fb2c9d74f

Hope this will help others too..

Thank you

**Comment by propertyhive** [comment]
@Shahab2905 Thanks so much for this. Using parts of the above we were able to add full support for this in version 1.1.17:

https://github.com/propertyhive/WP-Property-Hive/commit/b3c9a0a9bc99229d3b207874aa6fe44f7fd2a17e

This adds the classes when on the main search results page, and also when you've clicked into view a property.

Thanks again :)
