### ISSUE TITLE
Basic carousel feature

### ISSUE THREAD

**Issue by markheydon** [propertyhive/WP-Property-Hive#53]
Hi,

I wanted to add a Featured Property carousel to a clients project and after some research, I found the following post from somebody else wanting the same.

https://wordpress.org/support/topic/slider-242/

Try as I might though I couldn't get it working for the life of me, and was about to embark on a writing a plugin to add the feature when I noticed that the FlexSlider library is already being used for the property detail page, so thought it might be really cool to re-use that and add a basic slider shortcode instead of writing a plugin.

I have now got this working and tried to follow the existing style of the propertyhive code.  I've created a pull request of my efforts.

#52

Please bee kind as it's my first attempt at customising the propertyhive code!  If the code looks ok, I'd be happy to repeat the same for recent properties to complete the feature.  Would similar properties also need doing?

Mark

**Comment by markheydon** [comment]
Wrote extension plugin instead...

https://github.com/mhcg/property-carousel-propertyhive

https://wordpress.org/plugins/property-carousel-for-propertyhive/

**Comment by AlexMunch** [comment]
Hi Mark

How do I use this plugin?  I'm very new to all this.

Thanks
