### ISSUE TITLE
Min & Max Floor Area working incorrectly

### ISSUE THREAD

**Issue by JackAlexander1** [propertyhive/WP-Property-Hive#57]
Hi there,

I've been trying to use Min and Max Floor Area with Commercial Properties and it appears as if they don't work at all with how the currently keys are on the property post type.

The key the meta query is searching for is `_floor_area_from_sqft` however the existing key is called `_floor_area_from`. The same applies for `_floor_area_to`.

https://github.com/propertyhive/WP-Property-Hive/blob/master/includes/class-ph-query.php#L1215-L1265

**Comment by propertyhive** [comment]
Hi Jack, 

'_floor_area_from_sqft' is definitely a valid key. You can see it being used/updated here.

https://github.com/propertyhive/WP-Property-Hive/blob/master/includes/admin/post-types/meta-boxes/class-ph-meta-box-property-commercial-details.php#L603

Are you entering the properties manually into WordPress? Or are they being imported from somewhere else? I wonder if they're being imported maybe this key isn't being created?

Do let me know, 
Thanks,
Steve

**Comment by JackAlexander1** [comment]
Hi Steve,

So upon reevaluation of my custom import file for Alcium Commercial Properties, I set the `_floor_area_from` but didn't set the `_floor_area_from_sqft` and the same.

That's on me, I didn't realise that was necessary when creating the importer. I will remedy this and let you know if that fixes the issue. Thank you for the quick response!

Jack

**Comment by propertyhive** [comment]
No problem. The sqft key is there for ordering and efficient filtering so we have a unified value for all properties.
