### ISSUE TITLE
Property Import created corrupted files

### ISSUE THREAD

**Issue by JackAlexander1** [propertyhive/WP-Property-Hive#58]
Hi there,

I haven't had a problem with the importer until the last time I ran a Jupix import which afterwards had imported the images but they most were corrupted. It seems as if at a certain point during the import they stopped downloading properly. 

They'd been imported into the media library however the files dont exist. The same applies for PDF's that have been imported.

Is there a way we can re sync the files and get this sorted? What are the potential issues that may have caused this? 

Thanks,

Jack

Wordpress Ver: 4.9.5
PH Ver: 1.4.17

**Comment by propertyhive** [comment]
Hi Jack, 

We have the Jupix format running on tons of sites and have never seen a problem with images being 'corrupted' I'm afraid. 

"Is there a way we can re sync the files and get this sorted?"
- How many properties are we talking? You could delete/trash all the properties and let the import re-import them all again. That would work if its a small number of properties. If it's a large number of properties we're talking about, how many have corrupted/missing images?

"What are the potential issues that may have caused this?"
- It's hard to say. Like I say, we haven't seen this before. The only things I could think would be things like maybe the server is full, or maybe the media server on Jupix's end was having issues whilst we tried to retrieve the images. 

The only other time I've seen something similar to this (not Property hive related) is when you have specified the uploads path somewhere, maybe in the wp_options table or in wp-config.php, but that path doesn't exist or is wrong. This could occur when a site changes domain or is put live. not sure if this is a feasible possibility?

Let me know regarding the above, 
Thanks,
Steve
