### ISSUE TITLE
(feature request) pointing direct to property API's image

### ISSUE THREAD

**Issue by JackAlexander1** [propertyhive/WP-Property-Hive#59]
Hi there,

In relation to a previous issue (https://github.com/propertyhive/WP-Property-Hive/issues/58) I wanted to ask if it was possible to direct straight the property API's image rather then downloading the image to the media library as in some cases it has proven unreliable. 

Thanks,

Jack

**Comment by propertyhive** [comment]
Hi Jack, 

This is already on the feature roadmap:

https://trello.com/c/1dpCcDEB/196-core-option-to-store-media-as-urls

I'll be honest and say it's not a high priority as it's only come up as a request once before but is something we'll do at some point.

Regards, 
Steve
