### ISSUE TITLE
(feature request) Hide unticked "_on_market" properties from XML sitemap (Yoast)

### ISSUE THREAD

**Issue by JackAlexander1** [propertyhive/WP-Property-Hive#60]
Hi there,

A current issue we are currently having with a clients site is that the unticked "_on_market" properties that have been imported from Jupix and Alcium are currently getting indexed and therefore "ghost" properties are showing up on google results.

Is there an option to disable them from showing up or potentially could one be introduced? I think when the option is unset perhaps it makes the post a draft or private to prevent indexing?

Kind regards,

Jack

**Comment by propertyhive** [comment]
Hi Jack, 

When a property comes off the market it is no longer displayed in the search results or output in any shortcodes, however the URL remains active as to not end up with a bunch of 404 errors, which would be bad for SEO.

In the latest Property Hive release, if someone does end up accessing an off market property there is a message at the top now reading something along the lines of "This property is no longer on the market".

I think however we could introduce a new setting, or come up with a way to maybe 301 redirect off market property URLs, so maybe it does a 301 redirect to the search results page. What do you think of this? Open to suggestions.

Thanks,
Steve

**Comment by JackAlexander1** [comment]
Hi Steve,

I agree about the 404 errors and how it could be bad for SEO, but also I think properties appearing on google results that are supposed be off the feed isn't ideal. 

I didn't even realise that was a new option, I've completely overwritten the default single template so that hasn't appeared for me but I will check the plugin directory for that.

The idea of doing a 301 redirect I think would be the best idea for the situation. My suggestion for how this could be done would be using the action "template_redirect", detect if it is a single property page, check the meta to see if its off the market and then redirect to the Archive page if it is.

```
add_action( 'template_redirect', function (){
    if (is_singular('property')) {
        $on_market = get_post_meta(get_the_ID(), '_on_market');
        if ('' == $on_market[0]) {
            wp_redirect(get_post_type_archive_link('property'), 301);
            exit;
        }
    }
}, 5 );
```

That is just a quick bit I wrote for this, let me know your thoughts please.

Thanks,
Jack

**Comment by propertyhive** [comment]
Hi Jack, 

As this hasn't come up in over 2 years and we added a kind of workaround in the latest version with the addition of the message informing users the property is off the market, we've come to the decision that it would be beneficial to add the code you provided to our documentation for now, as opposed to making it a setting..

Should someone else raise this in the future we can then point them in the direction of our docs, and if it does end up coming up over and over again we can then look again at making it a setting.

If you need any help or advice with the code you've provided please let me know and I'll see what I can do to help.

Thanks,
Steve

**Comment by JackAlexander1** [comment]
Incase you were interested on how I disabled the propertys from appearing on the sitemaps, the following code snippet will do the trick.

```
add_filter('wpseo_exclude_from_sitemap_by_post_ids', function (){
        return get_posts([
            'fields'            => 'ids',
            'posts_per_page'    => -1,
            'post_type'         => 'property',
            'meta_query'        => [
                [
                    'key'   => '_on_market',
                    'value' => '',
                ]
            ]
       ]);
});
```

**Comment by propertyhive** [comment]
Hi Jack, 

I've added this a part of the next release to the existing Yoast compatibility functionality. Thanks for your input on this.

Steve
