### ISSUE TITLE
(Property Import) Jupix import - Failed to parse XML file turned every property Off the Market

### ISSUE THREAD

**Issue by JackAlexander1** [propertyhive/WP-Property-Hive#64]
Hi there,

Recently the Jupix importer ran and it turned every single property on there Off the Market, deleting all the media for all the properties. Upon further inspection of the logs, it seems that it Failed to parse XML file and didn't loop through the properties. It then proceeded to go through and mark all 1330 properties as off the market.

Do you know why it could have possibly done this as it took quite a while for the properties to be sorted back out again, this can't happen again. 

It was only for the one iteration of the import, the next hour it went back to importing as normal. I can provide the logs if needed.

Kind regards,

Jack

**Comment by propertyhive** [comment]
Hi Jack, 

What version of the import add on are you using as we made a change in version 1.0.80 which, from the changelog reads:

_"Don't continue processing Jupix XML if XML can't be parsed. In the past we've seen it where Jupix would be down or provide a blank XML file meaning all properties would be removed until the next import ran"_

Thanks,
Steve

**Comment by JackAlexander1** [comment]
Hi Steve,

Ah, good catch, we were on ver 1.0.78, I'm updating the plugin now!

Thanks Steve!

Jack
