### ISSUE TITLE
Bug found with ph_get_search_form

### ISSUE THREAD

**Issue by JackAlexander1** [propertyhive/WP-Property-Hive#85]
Hi there,

There seems to be an issue with the ph_get_search_form function where it loops through the $_REQUEST and checks for the $key against $form_controls. The "office" field changes to "officeID" in the ph_form_field function and when ph_get_search_form loops through the $_REQUEST, it doesn't recognise that officeID and office is the same field, creating a new hidden field called officeID.

This then makes it impossible to change the office has the hidden value will always override what field you have chosen in the dropdown.

https://github.com/propertyhive/WP-Property-Hive/blob/51ea28c8b4b1212524b44b5c63ddfbdb2247f6c6/includes/ph-form-functions.php#L37-L44

https://github.com/propertyhive/WP-Property-Hive/blob/51ea28c8b4b1212524b44b5c63ddfbdb2247f6c6/includes/ph-form-functions.php#L963-L965

**Comment by propertyhive** [comment]
@JackAlexander1 Good spot. Have corrected for the next version due to be released next week. 

Thanks for reporting :)

Steve
