### ISSUE TITLE
Failing to display search results

### ISSUE THREAD

**Issue by trendsetting** [propertyhive/WP-Property-Hive#9]
After a search, the program states "displaying X results", but no results are actually displayed.

**Comment by propertyhive** [comment]
Can you please try something for me. Go to 'Settings > Permalinks' and just hit 'Save' without changing anything. Does that resolve it?

I seem to remember having a similar problem before so, if this is the case again and this fixes it, I'll look at putting a fix in to fix this for others going forward.

Let me know how you get on. Thanks

**Comment by trendsetting** [comment]
The "save" on the permalinks does fix the problem.

**Comment by trendsetting** [comment]
Saving the permalinks does solve the problem.

**Comment by propertyhive** [comment]
This was fixed in version 1.1.0
