### ISSUE TITLE
Undefined variable $fieldset_class in class-ph-admin-settings.php after update to 1.4.45

### ISSUE THREAD

**Issue by benathomeofchampions** [propertyhive/WP-Property-Hive#97]
Following the update to 1.4.45, I am now seeing a notice on the admin settings page:

`Notice: Undefined variable: fieldset_class in /var/www/godfrey/wp-content/plugins/propertyhive/includes/admin/class-ph-admin-settings.php on line 488`

WordPress 5.2.2 on PHP 7.2.20

**Comment by propertyhive** [comment]
Thanks for this @benathomeofchampions . Have fixed for next release, likely to be out in a couple of weeks. Here's the commit should you wish to fix it manually for now:

https://github.com/propertyhive/WP-Property-Hive/commit/42d94a15c6397be47c8ba5f7d2637789c3ec0dbe

Thanks again!

Steve
