### ISSUE TITLE
PH 1.47 breaks Rest API for "availability" field

### ISSUE THREAD

**Issue by johnedwarddalton** [propertyhive/WP-Property-Hive#99]
In PH 1.46 and prior, a REST API call such as wp-json/wp/v2/property/1346 would populate the field for "availability" with the correct value .  In 1.47, the addition of the underscore at line 148 of class-ph-rest-api.php  class (  return $property->{'_' . $field_name}; ) means that a blank value is returned for custom fields such as "availability".  The result is that this field is now populated with an empty string

**Comment by propertyhive** [comment]
@johnedwarddalton You're absolutely right, and I appreciate you taking the time to report this. 

This has been corrected with immediate effect and will be part of the next release, likely early next week. If you wish to add the change manually in the meantime I've included it below:

https://github.com/propertyhive/WP-Property-Hive/commit/1c34b58e2f466a88b05ac7102fcb641a9d6de71a

Essentially, for now I've just reverted it to how it was before until we can re-visit this.

Thanks again, 
Steve
